# build_supply_layer.ps1
# Builds data/supply_data.js -> window.SUPPLY, the data behind the Find a Supplier tool:
# every licensed customs clearing agent, plus the input side of mining (reagents, explosives,
# equipment, freight, assay, fuel, fabrication) from the sector directory.
#
# Contact values NEVER enter this file. The app is deployed publicly, so view-source would
# expose anything shipped in data/. What ships is: name, what they do, town, licence type,
# registry standing, and a HAS-CONTACT FLAG - enough to pick a supplier and know a channel
# exists, with the channel itself held in private/.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Has($v) { $v -and "$v".Trim() -and "$v" -notmatch '^(n/?a|none|null|not found|-)$' }

# ---------- customs clearing agents (ZRA licensed register) ----------
$agents = @(Import-Csv (Join-Path $root 'dataset\clearing_agents_public.csv'))
# the private copy supplies ONLY a boolean: does a channel exist for this agent?
$reach = @{}
$privAgents = Join-Path $root 'private\dataset\clearing_agents.csv'
if (Test-Path $privAgents) {
    foreach ($r in (Import-Csv $privAgents)) {
        if ((Has $r.phone) -or (Has $r.email)) { $reach[$r.name] = 1 }
    }
}
$agentRows = foreach ($a in $agents) {
    [pscustomobject]@{
        n = $a.name
        t = $a.town
        lic = $a.licence_type
        exp = $a.expiry
        ch = [int]([bool]$reach[$a.name])
    }
}
$agentRows = @($agentRows)
Write-Host ("clearing agents: {0}  ({1} with a private channel, {2} located)" -f `
    $agentRows.Count, @($agentRows | Where-Object { $_.ch }).Count, @($agentRows | Where-Object { $_.t }).Count)

# ---------- input suppliers (sector directory) ----------
# Grouped into the buckets a buyer actually shops by, not by ISIC.
$BUCKETS = @{
    'consumables_reagents' = 'Reagents & process chemicals'
    'explosives'           = 'Explosives & blasting'
    'equipment_dealer'     = 'Equipment & spares'
    'drilling'             = 'Drilling contractors'
    'mining_contractor'    = 'Mining contractors'
    'engineering_epcm'     = 'Engineering & EPCM'
    'assay_lab'            = 'Assay & inspection labs'
    'geo_consultancy'      = 'Geological consultancies'
    'freight_clearing'     = 'Freight forwarders'
    'haulage'              = 'Road haulage'
    'rail'                 = 'Rail freight'
    'power_fuel'           = 'Fuel & power'
    'tailings_water'       = 'Tailings & water treatment'
    'security'             = 'Site security'
    'smelter_refiner'      = 'Smelters & refiners'
    'processor'            = 'Processing plants'
    'scrap_metal'          = 'Scrap & recycling'
    'lapidary'             = 'Lapidaries'
    'gemstone_dealer'      = 'Gemstone dealers'
    'gold_buyer'           = 'Gold buyers'
    'trader'               = 'Mineral traders'
    'export_intermediary'  = 'Export intermediaries'
}
$biz = @(Import-Csv (Join-Path $root 'dataset\mining_businesses.csv'))
# channel flag from the private research files
$bizReach = @{}
foreach ($f in 'biz_traders_processors.json','biz_services_supply.json','biz_enriched_batchA.json') {
    $p = Join-Path $root "private\research\$f"
    if (-not (Test-Path $p)) { continue }
    foreach ($b in (([System.IO.File]::ReadAllText($p, $utf8) | ConvertFrom-Json) | ForEach-Object { $_ })) {
        $c = $b.contact
        if ($c -and ((Has $c.website) -or (Has $c.email) -or (Has $c.phone))) { $bizReach[$b.name] = 1 }
    }
}
$supRows = foreach ($b in $biz) {
    [pscustomobject]@{
        n = $b.name
        seg = $b.segment
        lbl = if ($BUCKETS[$b.segment]) { $BUCKETS[$b.segment] } else { ($b.segment -replace '_',' ') }
        w = $b.what_they_do
        t = $b.town
        p = $b.province
        own = $b.ownership
        pn = $b.pacra_number
        ps = $b.pacra_status
        ch = [int]([bool]$bizReach[$b.name])
        lat = if (Has $b.lat) { [double]$b.lat } else { $null }
        lng = if (Has $b.lng) { [double]$b.lng } else { $null }
    }
}
$supRows = @($supRows)
Write-Host ("input suppliers: {0}  ({1} with a channel, {2} located to a town, {3} mapped)" -f `
    $supRows.Count, @($supRows | Where-Object { $_.ch }).Count,
    @($supRows | Where-Object { Has $_.t }).Count, @($supRows | Where-Object { $_.lat }).Count)

# ---------- emit ----------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* supply_data.js - generated by pipeline/build_supply_layer.ps1. Do not hand-edit.')
[void]$sb.AppendLine('   Licensed customs clearing agents (ZRA register, 31.05.2024) and mining input suppliers.')
[void]$sb.AppendLine('   Contact VALUES are held in private/ and never emitted here - only a has-channel flag. */')
[void]$sb.AppendLine('window.SUPPLY = {')
[void]$sb.AppendLine('meta: {agentSource: "ZRA Licensed Clearing Agents Schedule as at 31.05.2024", agentUrl: "https://www.zra.org.zm/clearing-agents/"},')
[void]$sb.Append('BUCKETS: ')
[void]$sb.Append((ConvertTo-Json $BUCKETS -Compress))
[void]$sb.AppendLine(',')
[void]$sb.Append('AGENTS: ')
[void]$sb.Append((ConvertTo-Json $agentRows -Depth 3 -Compress))
[void]$sb.AppendLine(',')
[void]$sb.Append('SUPPLIERS: ')
[void]$sb.Append((ConvertTo-Json $supRows -Depth 3 -Compress))
[void]$sb.AppendLine('};')

$out = Join-Path $root 'data\supply_data.js'
[System.IO.File]::WriteAllText($out, $sb.ToString(), $utf8)
Write-Host ("`nwrote {0}  ({1:N0} KB)" -f $out, ((Get-Item $out).Length / 1kb))

# ---------- privacy assertion ----------
$txt = [System.IO.File]::ReadAllText($out, $utf8)
$ph = ([regex]::Matches($txt, '\+ ?260[0-9 \-]{7,}|\b0[976][0-9]{8}\b')).Count
$em = ([regex]::Matches($txt, '[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}')).Count
Write-Host ("PRIVACY CHECK on the emitted file: phones={0} emails={1}" -f $ph, $em)
if ($ph -gt 0 -or $em -gt 0) { throw "contact values leaked into data/supply_data.js - refusing to ship" }
