# build_kyc_court.ps1
# Converts the ZambiaLII scrape checkpoint (data\gov\court\court_hits.json) into the
# web layer data\kyc_court.js -> window.KYC_COURT (names with >=1 judgment hit only).
# Re-run any time; picks up whatever the (resumable) scraper has checkpointed so far.
#
# Usage: powershell -ExecutionPolicy Bypass -File pipeline\build_kyc_court.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $root 'data\gov\court\court_hits.json'
if (-not (Test-Path $src)) { Write-Host "No checkpoint at $src"; exit 1 }

$j = Get-Content $src -Raw | ConvertFrom-Json

function Esc([string]$s) {
    if ($null -eq $s) { return "" }
    return $s.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", ' ').Trim()
}

$total = 0; $withHits = 0
$entries = New-Object System.Collections.Generic.List[string]
foreach ($prop in $j.names.PSObject.Properties) {
    $total++
    $v = $prop.Value
    if (-not $v.n -or $v.n -lt 1) { continue }
    $withHits++
    $hits = @()
    foreach ($h in $v.hits) {
        $u = "$($h.u)"
        if ($u -and -not $u.StartsWith('http')) { $u = "https://zambialii.org$u" }
        $hits += ('{"t":"' + (Esc $h.t) + '","d":"' + (Esc $h.d) + '","c":"' + (Esc $h.c) + '","u":"' + (Esc $u) + '"}')
    }
    $entries.Add('"' + (Esc $prop.Name.ToUpper()) + '":{"n":' + [int]$v.n + ',"hits":[' + ($hits -join ',') + ']}')
}

$js = "// Generated by pipeline/build_kyc_court.ps1 - do not edit by hand`n" +
      "// Source: ZambiaLII judgment search ($($j.endpoint))`n" +
      "window.KYC_COURT = {meta:{scraped:""$(Esc $j.scraped)"",namesQueried:$total,namesWithHits:$withHits},names:{`n" +
      ($entries -join ",`n") + "`n}};`n"
[System.IO.File]::WriteAllText((Join-Path $root 'data\kyc_court.js'), $js, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote data\kyc_court.js  ($total names queried, $withHits with hits)"
