# build_license_polygons.ps1
# Converts the NGDR active-license polygons into a lean web layer:
#   data\licenses_geo.js  ->  window.LICENSES_GEO (GeoJSON FeatureCollection)
# - coordinates rounded to 4 decimals (~11 m)
# - properties reduced to: c=code, t=typecode, h=holder, m=commodities, e=expires(YYYY-MM), a=hectares, f=flag
# - flag joined from the official MMMD cancellation/default lists (same rule as build_license_layer.ps1)
#
# Usage: powershell -ExecutionPolicy Bypass -File pipeline\build_license_polygons.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$gov  = Join-Path $root 'data\gov'

Add-Type -AssemblyName System.Web.Extensions
$ser = New-Object System.Web.Script.Serialization.JavaScriptSerializer
$ser.MaxJsonLength = [int]::MaxValue
$ser.RecursionLimit = 1000

Write-Host "Loading NGDR polygons (13 MB)..."
$raw = [System.IO.File]::ReadAllText((Join-Path $gov 'ngdr\ngdr_active_mining_licenses.geojson'))
$gj = $ser.DeserializeObject($raw)
$features = $gj['features']
Write-Host "  $($features.Count) features"

Write-Host "Loading adverse lists..."
$mlc  = $ser.DeserializeObject([System.IO.File]::ReadAllText((Join-Path $gov 'mmmd_mlc78_cancellations_2024-04.json')))
$dn25 = $ser.DeserializeObject([System.IO.File]::ReadAllText((Join-Path $gov 'mmmd_default_notice_2025-06-18.json')))
$cancelled = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($r in $mlc)  { if ($r['code']) { [void]$cancelled.Add($r['code'].Trim().ToUpper()) } }
$inDefault = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($r in $dn25) { if ($r['code']) { [void]$inDefault.Add($r['code'].Trim().ToUpper()) } }

function Esc([string]$s) {
    if ($null -eq $s) { return "" }
    return $s.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", ' ').Trim()
}

$inv = [System.Globalization.CultureInfo]::InvariantCulture
$sb = New-Object System.Text.StringBuilder (20MB)
[void]$sb.Append("// Generated by pipeline/build_license_polygons.ps1 - do not edit by hand`n")
[void]$sb.Append("// NGDR GeoServer active-license polygons, 4-decimal precision, flags joined from MMMD lists.`n")
[void]$sb.Append('window.LICENSES_GEO = {"type":"FeatureCollection","features":[')

$n = 0; $skipped = 0
foreach ($f in $features) {
    $p = $f['properties']
    $g = $f['geometry']
    if ($null -eq $p -or $null -eq $g -or -not $p['code'] -or $null -eq $g['coordinates']) { $skipped++; continue }

    $code = $p['code'].Trim().ToUpper()
    $flag = 0
    if ($inDefault.Contains($code)) { $flag = $flag -bor 1 }
    if ($cancelled.Contains($code)) { $flag = $flag -bor 2 }

    $exp = ""
    if ($p['dteexpires'] -and $p['dteexpires'].Length -ge 7) { $exp = $p['dteexpires'].Substring(0, 7) }
    $ha = 0
    if ($p['areavalue']) { $ha = [math]::Round([double]$p['areavalue'], 0) }

    # geometry: normalize to MultiPolygon nesting, round coords.
    # NOTE: plain assignments only — `$x = if (...) { $arr }` pipeline-unrolls
    # single-element arrays and silently corrupts the nesting (the bug that
    # shipped [lng,0],[lat,0] point pairs the first time).
    $coords = $g['coordinates']
    $polys = $coords
    if ($g['type'] -ne 'MultiPolygon') {
        $tmp = New-Object 'object[]' 1
        $tmp[0] = $coords
        $polys = $tmp
    }
    $gsb = New-Object System.Text.StringBuilder
    [void]$gsb.Append('[')
    $minX = 999.0; $maxX = -999.0; $minY = 999.0; $maxY = -999.0
    $geomOk = $true
    $pi = 0
    foreach ($poly in $polys) {
        if (-not $geomOk) { break }
        if ($pi++ -gt 0) { [void]$gsb.Append(',') }
        [void]$gsb.Append('[')
        $ri = 0
        foreach ($ring in $poly) {
            if (-not $geomOk) { break }
            if ($ri++ -gt 0) { [void]$gsb.Append(',') }
            [void]$gsb.Append('[')
            $vi = 0
            foreach ($v in $ring) {
                # each vertex must be an [x, y] list — anything else means the
                # nesting is off for this feature; drop it rather than emit garbage
                if ($v -isnot [System.Collections.IList] -or $v.Count -lt 2) { $geomOk = $false; break }
                if ($vi++ -gt 0) { [void]$gsb.Append(',') }
                $xd = [double]$v[0]; $yd = [double]$v[1]
                if ($xd -lt $minX) { $minX = $xd }; if ($xd -gt $maxX) { $maxX = $xd }
                if ($yd -lt $minY) { $minY = $yd }; if ($yd -gt $maxY) { $maxY = $yd }
                $x = [math]::Round($xd, 4).ToString($inv)
                $y = [math]::Round($yd, 4).ToString($inv)
                [void]$gsb.Append("[$x,$y]")
            }
            [void]$gsb.Append(']')
        }
        [void]$gsb.Append(']')
    }
    [void]$gsb.Append(']')
    # sanity: parcel must sit inside Zambia's bounding box
    if (-not $geomOk -or $minX -lt 21 -or $maxX -gt 35 -or $minY -lt -19 -or $maxY -gt -7) { $skipped++; continue }

    if ($n -gt 0) { [void]$sb.Append(',') }
    [void]$sb.Append("`n")
    [void]$sb.Append('{"type":"Feature","properties":{"c":"' + (Esc $code) + '","t":"' + (Esc $p['typecode']) + '","h":"' + (Esc $p['parties']) + '","m":"' + (Esc $p['commoditie']) + '","e":"' + $exp + '","a":' + $ha + ',"f":' + $flag + '},"geometry":{"type":"MultiPolygon","coordinates":' + $gsb.ToString() + '}}')
    $n++
    if ($n % 500 -eq 0) { Write-Host "  $n features processed..." }
}

[void]$sb.Append("`n]};`n")
[System.IO.File]::WriteAllText((Join-Path $root 'data\licenses_geo.js'), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
$mb = [math]::Round((Get-Item (Join-Path $root 'data\licenses_geo.js')).Length / 1MB, 2)
Write-Host "Wrote data\licenses_geo.js  ($n features, $skipped skipped, $mb MB)"
