# build_production_layer.ps1
# Converts data\gov\production\production.json (EITI Fusion portal + ZEITI XLSX extracts)
# into the web layer data\production_data.js -> window.PRODUCTION.
# Canonicalizes company-name variants and merges the FQM Trident / Kalumbila (Sentinel)
# overlap, preferring portal tonnages and keeping ZEITI 2023 USD values.
#
# Usage: powershell -ExecutionPolicy Bypass -File pipeline\build_production_layer.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $root 'data\gov\production\production.json'
$pr = Get-Content $src -Raw | ConvertFrom-Json

function Canon([string]$name) {
    $n = ($name -replace '\(\s*\d+(\.\d+)?\s*%\s*\)', '' -replace '\s+', ' ').Trim().ToUpperInvariant()
    if ($n -like 'FQM TRIDENT*' -or $n -like 'KALUMBILA*') { return 'KALUMBILA' }
    if ($n -like 'KANSANSHI*') { return 'KANSANSHI' }
    if ($n -like 'KONKOLA*') { return 'KCM' }
    if ($n -like 'MOPANI*') { return 'MOPANI' }
    if ($n -like 'LUMWANA*') { return 'LUMWANA' }
    if ($n -like 'CNMC LUANSHYA*') { return 'LUANSHYA' }
    if ($n -like 'CHAMBISHI COPPER SMELTER*') { return 'CCS' }
    if ($n -like 'CHAMBISHI METALS*') { return 'CHAMBISHI METALS' }
    if ($n -like 'NFC AFRICA*') { return 'NFCA' }
    if ($n -like 'SINO-METALS*') { return 'SINO-METALS' }
    if ($n -like 'LUBAMBE*') { return 'LUBAMBE' }
    if ($n -like 'CHIBULUMA*') { return 'CHIBULUMA' }
    if ($n -like 'MIMBULA*') { return 'MIMBULA' }
    if ($n -like 'OTHER MINES*') { return 'OTHER' }
    return $n
}
$display = @{
    KANSANSHI = 'Kansanshi Mining Plc (FQM)'; KALUMBILA = 'Kalumbila Minerals / Sentinel (FQM Trident)'
    KCM = 'Konkola Copper Mines Plc'; MOPANI = 'Mopani Copper Mines Plc'
    LUMWANA = 'Lumwana Mining Co. (Barrick)'; LUANSHYA = 'CNMC Luanshya Copper Mines'
    CCS = 'Chambishi Copper Smelter Ltd'; 'CHAMBISHI METALS' = 'Chambishi Metals Plc'
    NFCA = 'NFC Africa Mining Plc'; 'SINO-METALS' = 'Sino-Metals Leach Zambia Ltd'
    LUBAMBE = 'Lubambe Copper Mine Ltd'; CHIBULUMA = 'Chibuluma Mines Plc'
    MIMBULA = 'Mimbula Minerals'; OTHER = 'Other mines'
}

$companies = @{}
foreach ($row in $pr.companyProduction) {
    if ($row.commodity -ne 'Copper') { continue }
    $key = Canon $row.company
    if (-not $companies.ContainsKey($key)) {
        $companies[$key] = @{ key = $key; display = $(if ($display.ContainsKey($key)) { $display[$key] } else { $row.company }); series = @{}; larger = @{}; usd2023 = $null }
    }
    $c = $companies[$key]
    $y = [string]$row.year
    $v = [math]::Round([double]$row.volume, 0)
    # On alias merges (e.g. FQM Trident vs Kalumbila, same Sentinel operation) keep
    # the LARGER figure for a year — the sparse duplicate rows are partial extracts.
    if (-not $c.series.ContainsKey($y) -or $v -gt $c.series[$y]) { $c.series[$y] = $v }
    if ($row.year -eq 2023 -and $row.PSObject.Properties['valueUsd'] -and $row.valueUsd) { $c.usd2023 = [math]::Round([double]$row.valueUsd, 0) }
}

# national totals: copper/cobalt/gold only, values published in thousand tonnes for base metals
$national = @()
foreach ($row in $pr.nationalProductionByCommodity) {
    if ($row.commodity -match 'Copper Prod|Cobalt Prod|Gold Prod') {
        $national += [pscustomobject]@{ commodity = ($row.commodity -replace ' Prod.*', ''); year = $row.year; volume = $row.volume }
    }
}

# top 2023 exports by ZMW value
$exp = $pr.exportsByCommodity | Where-Object { $_.year -eq 2023 -and $_.valueZmw } |
    Sort-Object { [double]$_.valueZmw } -Descending | Select-Object -First 6

function Esc([string]$s) { if ($null -eq $s) { return "" } return $s.Replace('\', '\\').Replace('"', '\"') }

$compJson = ($companies.Values | Sort-Object { -([double]($_.series['2023'])) } | ForEach-Object {
    $ser = ($_.series.GetEnumerator() | Sort-Object Name | ForEach-Object { '"' + $_.Name + '":' + $_.Value }) -join ','
    '{"key":"' + (Esc $_.key) + '","display":"' + (Esc $_.display) + '","series":{' + $ser + '}' +
    $(if ($_.usd2023) { ',"usd2023":' + $_.usd2023 } else { '' }) + '}'
}) -join ",`n"

$natJson = ($national | ForEach-Object { '{"c":"' + (Esc $_.commodity) + '","y":' + $_.year + ',"v":' + $_.volume + '}' }) -join ','
$expJson = ($exp | ForEach-Object { '{"c":"' + (Esc $_.commodity) + '","kg":' + [math]::Round([double]$_.volume,0) + ',"zmw":' + [math]::Round([double]$_.valueZmw,0) + '}' }) -join ",`n"

$js = "// Generated by pipeline/build_production_layer.ps1 - do not edit by hand`n" +
      "// Sources: Zambia EITI Fusion portal datasets + ZEITI 'Copper Production by Company 2023' XLSX + 2023 customs exports XLSX`n" +
      "window.PRODUCTION = {`n" +
      'meta: {note: "Company copper production 2018-2023 (tonnes). Portal tonnages preferred; USD values from ZEITI 2023 file. 2024 by-company data is not published. National base-metal totals are in THOUSAND tonnes as published."},' + "`n" +
      "companies: [`n$compJson`n],`n" +
      "national: [$natJson],`n" +
      "exports2023: [`n$expJson`n]};`n"
[System.IO.File]::WriteAllText((Join-Path $root 'data\production_data.js'), $js, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote data\production_data.js  ($($companies.Count) companies, $($national.Count) national rows, $(@($exp).Count) export rows)"
