# build_license_layer.ps1
# Joins the NGDR GeoServer active-license polygons (open government WFS) with the
# official MMMD cancellation / default-notice lists, and emits a compact
# centroid-point layer for the web map: data\licenses_points.js
#
# Inputs (downloaded by the research step into data\gov\):
#   ngdr\ngdr_active_mining_licenses.geojson   - active licenses (MultiPolygon, holder/type/dates)
#   mmmd_mlc78_cancellations_2024-04.json      - MLC 78th-meeting cancellations (Apr 2024)
#   mmmd_default_notice_2025-06-18.json        - Final Public Default Notice (Jun 2025)
#
# Usage: powershell -ExecutionPolicy Bypass -File pipeline\build_license_layer.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$gov  = Join-Path $root 'data\gov'

Write-Host "Loading NGDR licenses..."
$ngdr = Get-Content (Join-Path $gov 'ngdr\ngdr_active_mining_licenses.geojson') -Raw | ConvertFrom-Json
Write-Host "  $($ngdr.features.Count) features"

Write-Host "Loading revocation lists..."
$mlc  = Get-Content (Join-Path $gov 'mmmd_mlc78_cancellations_2024-04.json') -Raw | ConvertFrom-Json
$dn25 = Get-Content (Join-Path $gov 'mmmd_default_notice_2025-06-18.json') -Raw | ConvertFrom-Json

$cancelled = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($r in $mlc) { [void]$cancelled.Add($r.code.Trim().ToUpper()) }
$inDefault = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($r in $dn25) { [void]$inDefault.Add($r.code.Trim().ToUpper()) }
Write-Host "  cancelled codes: $($cancelled.Count); default codes: $($inDefault.Count)"

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("// Generated by pipeline/build_license_layer.ps1 - do not edit by hand`n")
[void]$sb.Append("// Source: NGDR GeoServer (geoserverprd.gsb.gov.zm, open WFS) snapshot + official MMMD notices`n")
[void]$sb.Append("// Point = polygon centroid. Fields: [lng, lat, code, typecode, holder, commodities, expires, hectares, flag]`n")
[void]$sb.Append("// flag: 0=none, 1=in Jun-2025 Final Default Notice, 2=cancelled at MLC-78 (Apr 2024), 3=both`n")

$stats = @{}
$flagged = 0
$rows = New-Object System.Collections.Generic.List[string]

function Esc([string]$s) {
    if ($null -eq $s) { return "" }
    return $s.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", ' ')
}

foreach ($f in $ngdr.features) {
    $p = $f.properties
    if (-not $p.code) { continue }

    # centroid of first outer ring (display purposes only)
    $g = $f.geometry
    if ($null -eq $g -or $null -eq $g.coordinates) { continue }
    $ring = if ($g.type -eq 'MultiPolygon') { $g.coordinates[0][0] } else { $g.coordinates[0] }
    if ($null -eq $ring -or $ring.Count -lt 3) { continue }
    $sx = 0.0; $sy = 0.0
    foreach ($pt in $ring) { $sx += [double]$pt[0]; $sy += [double]$pt[1] }
    $lng = [math]::Round($sx / $ring.Count, 4)
    $lat = [math]::Round($sy / $ring.Count, 4)
    if ($lng -lt 21 -or $lng -gt 34.5 -or $lat -lt -18.5 -or $lat -gt -8) { continue }

    $code = $p.code.Trim().ToUpper()
    $flag = 0
    if ($inDefault.Contains($code)) { $flag = $flag -bor 1 }
    if ($cancelled.Contains($code)) { $flag = $flag -bor 2 }
    if ($flag -gt 0) { $flagged++ }

    $tc = if ($p.typecode) { $p.typecode } else { '?' }
    if (-not $stats.ContainsKey($tc)) { $stats[$tc] = 0 }
    $stats[$tc]++

    $holder = Esc $p.parties
    $comm   = Esc $p.commoditie
    $exp    = if ($p.dteexpires) { $p.dteexpires.Substring(0, 7) } else { "" }
    $ha     = if ($p.areavalue) { [math]::Round([double]$p.areavalue, 0) } else { 0 }

    $rows.Add("[$lng,$lat,`"$code`",`"$tc`",`"$holder`",`"$comm`",`"$exp`",$ha,$flag]")
}

[void]$sb.Append("window.LICENSES = {`n")
[void]$sb.Append('meta: {source: "NGDR GeoServer open WFS (gsb.gov.zm) + MMMD official notices", snapshot: "' + (Get-Date).ToString('yyyy-MM-dd') + '", note: "First 5,000 of ~7,468 active licenses (WFS page cap). Centroids only; polygons in data/gov/."},' + "`n")
[void]$sb.Append("byType: " + ($stats | ConvertTo-Json -Compress) + ",`n")
[void]$sb.Append("points: [`n" + ($rows -join ",`n") + "`n]};`n")

[System.IO.File]::WriteAllText((Join-Path $root 'data\licenses_points.js'), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote data\licenses_points.js  ($($rows.Count) points, $flagged flagged)"
Write-Host ("By type: " + (($stats.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ', '))
