# build_kyc_data.ps1
# Emits data\kyc_data.js: the three official MMMD adverse lists in compact form
# for the in-browser KYC / counterparty check.
#   lists: mlc78  - MLC 78th-meeting cancellations (Apr 2024)
#          dn2025 - Final Public Default Notice (18 Jun 2025)
#          dn2023 - Default notice (Oct 2023)
# Row format: [code, holder, detail]
#
# Usage: powershell -ExecutionPolicy Bypass -File pipeline\build_kyc_data.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$gov  = Join-Path $root 'data\gov'

function Esc([string]$s) {
    if ($null -eq $s) { return "" }
    return $s.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", ' ').Trim()
}

# The 2025 notice's breachSection strings were truncated at the page wrap in the
# source PDF (all 5 distinct types end mid-citation). Normalize each to a complete,
# correctly-cited description drawn from the notice's own preamble + statute.
function NormalizeBreach([string]$s) {
    if ([string]::IsNullOrWhiteSpace($s)) { return "" }
    $t = ($s -replace '\s+', ' ').Trim()
    if ($t -match '^Non-?\s*Registration of Pegging') {
        return 'Non-registration of pegging certificate within 180 days of grant, contrary to s.18(2) of the Mines and Minerals Development Act No. 11 of 2015 (K120,000 penalty)'
    }
    if ($t -match 'Monthly Mineral Production Report') {
        return 'Non-submission of monthly mineral production reports, contrary to the Mines and Minerals Development (General) Regulations 2016'
    }
    if ($t -match 'Non-?Payment.*area charges|area charges - Section 77') {
        return 'Non-payment of annual area charges, contrary to s.77 of the Act and Regulation 57(3) of the General Regulations 2016 (K200,000 penalty)'
    }
    if ($t -match 'Annual Reports Contrary to Regulation 51') {
        return 'Non-submission of annual reports, contrary to Regulation 51 of the Mines and Minerals Development (General) Regulations 2016'
    }
    if ($t -match 'Future Program of Operations') {
        return 'Non-submission of the future programme of operations report, contrary to the General Regulations 2016'
    }
    return $t  # unknown pattern — keep as-is
}

$out = New-Object System.Text.StringBuilder
[void]$out.Append("// Generated by pipeline/build_kyc_data.ps1 - do not edit by hand`n")
[void]$out.Append("// Official MMMD adverse lists for the KYC check. Row: [code, holder, detail]`n")
[void]$out.Append("window.KYC = { lists: {`n")

$specs = @(
    @{ id = 'mlc78';  file = 'mmmd_mlc78_cancellations_2024-04.json'; label = 'Cancelled — MLC 78th meeting (Apr 2024)';    detail = { param($r) if ($r.comment) { $r.comment } else { $r.decision } } },
    @{ id = 'dn2025'; file = 'mmmd_default_notice_2025-06-18.json';   label = 'Final Public Default Notice (18 Jun 2025)'; detail = { param($r) NormalizeBreach $r.breachSection } },
    @{ id = 'dn2023'; file = 'mmmd_default_notice_2023-10.json';      label = 'Default notice (Oct 2023)';                 detail = { param($r) "" } }
)

foreach ($s in $specs) {
    $recs = Get-Content (Join-Path $gov $s.file) -Raw | ConvertFrom-Json
    $rows = New-Object System.Collections.Generic.List[string]
    foreach ($r in $recs) {
        if (-not $r.code) { continue }
        $rows.Add('["' + (Esc $r.code) + '","' + (Esc $r.holder) + '","' + (Esc (& $s.detail $r)) + '"]')
    }
    [void]$out.Append('"' + $s.id + '": {label: "' + $s.label + '", rows: [' + "`n" + ($rows -join ",`n") + "`n]},`n")
    Write-Host "$($s.id): $($rows.Count) rows"
}

[void]$out.Append("}};`n")
[System.IO.File]::WriteAllText((Join-Path $root 'data\kyc_data.js'), $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote data\kyc_data.js"
