# fetch_trade_data.ps1
# Pulls Zambian copper/cobalt trade data from the free UN Comtrade public preview API
# (no API key required; preview responses are capped at 500 records per call and the
# endpoint accepts ONE period per call and rate-limits aggressively).
# Emits data\raw\*.json (raw API responses) and data\trade_data.js (flat rows for the frontend).
#
# Usage:  powershell -ExecutionPolicy Bypass -File pipeline\fetch_trade_data.ps1

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$root   = Split-Path -Parent $PSScriptRoot
$rawDir = Join-Path $root 'data\raw'
if (-not (Test-Path $rawDir)) { New-Item -ItemType Directory -Force $rawDir | Out-Null }

$base = 'https://comtradeapi.un.org/public/v1/preview/C'
# Collapse mode-of-transport / customs-procedure / second-partner duplicates to one TOTAL row
$flt  = 'motCode=0&customsCode=C00&partner2Code=0'

$years        = 2019..2024
$codes        = @('740311','2603','7402','7404','7408','8105')
$monthlyCodes = @('740311','2603')
$months       = @()
foreach ($y in 2023..2024) { foreach ($m in 1..12) { $months += ('{0}{1:d2}' -f $y, $m) } }

$queries = New-Object System.Collections.Generic.List[object]
foreach ($c in $codes) {
    foreach ($y in $years) {
        # Zambia-reported exports, all partners
        $queries.Add([pscustomobject]@{ name = "X_A_${c}_$y";  url = "$base/A/HS?reporterCode=894&flowCode=X&cmdCode=$c&period=$y&$flt" })
        # Mirror: all reporters' imports FROM Zambia
        $queries.Add([pscustomobject]@{ name = "MM_A_${c}_$y"; url = "$base/A/HS?partnerCode=894&flowCode=M&cmdCode=$c&period=$y&$flt" })
    }
}
foreach ($c in $monthlyCodes) {
    foreach ($p in $months) {
        $queries.Add([pscustomobject]@{ name = "X_M_${c}_$p"; url = "$base/M/HS?reporterCode=894&flowCode=X&cmdCode=$c&period=$p&$flt" })
    }
}

Write-Host "Planned queries: $($queries.Count)"
$rows = New-Object System.Collections.Generic.List[object]
$truncated = @()
$failed = @()
$i = 0

foreach ($q in $queries) {
    $i++
    $outFile = Join-Path $rawDir "$($q.name).json"

    # Resume support: skip queries already fetched
    if (Test-Path $outFile) {
        $resp = Get-Content $outFile -Raw | ConvertFrom-Json
    } else {
        $resp = $null
        for ($try = 1; $try -le 5 -and $null -eq $resp; $try++) {
            try {
                $resp = Invoke-RestMethod -Uri $q.url -TimeoutSec 60
            } catch {
                $msg = $_.Exception.Message
                if ($msg -match '429') { $wait = 20 * $try } else { $wait = 5 * $try }
                Write-Warning "[$i/$($queries.Count)] $($q.name) attempt $try failed ($msg); waiting ${wait}s"
                Start-Sleep -Seconds $wait
            }
        }
        if ($null -eq $resp) { $failed += $q.name; continue }
        $resp | ConvertTo-Json -Depth 6 -Compress | Out-File -FilePath $outFile -Encoding utf8
        Start-Sleep -Seconds 6
    }

    if ($resp.count -ge 500) { $truncated += $q.name }
    foreach ($d in $resp.data) {
        if ($d.motCode -ne 0 -or $d.customsCode -ne 'C00' -or $d.partner2Code -ne 0) { continue }
        $rows.Add([pscustomobject]@{
            freq   = $d.freqCode
            period = "$($d.period)"
            flow   = $d.flowCode
            rep    = $d.reporterCode
            par    = $d.partnerCode
            code   = $d.cmdCode
            kg     = $d.netWgt
            usd    = $d.primaryValue
        })
    }
    if ($i % 10 -eq 0) { Write-Host "[$i/$($queries.Count)] done; rows so far: $($rows.Count)" }
}

Write-Host "Total rows kept: $($rows.Count)"
if ($truncated.Count) { Write-Warning ("At 500-row preview cap (possibly truncated): " + ($truncated -join ', ')) }
if ($failed.Count)    { Write-Warning ("Failed queries: " + ($failed -join ', ')) }

$meta = [pscustomobject]@{
    source    = 'UN Comtrade public preview API (comtradeapi.un.org/public/v1/preview)'
    fetched   = (Get-Date).ToString('yyyy-MM-dd')
    note      = 'Free preview tier, 500-record cap per query. TOTAL rows only (motCode=0, customsCode=C00, partner2Code=0).'
    truncated = @($truncated)
    failed    = @($failed)
}

$rowsJson = ConvertTo-Json -InputObject $rows.ToArray() -Compress -Depth 3
$metaJson = ConvertTo-Json -InputObject $meta -Compress -Depth 3
$js = "// Generated by pipeline/fetch_trade_data.ps1 - do not edit by hand`n" +
      "window.TRADE_META = $metaJson;`n" +
      "window.TRADE_ROWS = $rowsJson;`n"
[System.IO.File]::WriteAllText((Join-Path $root 'data\trade_data.js'), $js, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote data\trade_data.js"
